### ISSUE TITLE
visNetwork?

### ISSUE THREAD

**Issue by TomHarrop** [guillaumelobet/psim#1]
Hi Guillaume,

So you've already shared a package you made at the airport? That's pretty impressive ;)

We're having a couple of problems getting it to run.

Firstly it can't install `visNetwork` because it's not on CRAN (I got around it with `devtools::install_git('https://github.com/dataknowledge/visNetwork')`)

After that your package installed and shiny app launched, but (maybe related to the first problem) we are getting an error `unused argument (style = 'arrow')` in the web app when we click the `Unleash` button. In the terminal the error is `Error in visEdges(., style = "arrow") : unused argument (style = "arrow")`

Maybe I got the wrong `visNetwork` fork?

Thanks!

Tom

**Comment by guillaumelobet** [comment]
Hey Tom, 

Thanks for the nice comments :) Actually I cheated a little bit, I finished it today ...

Normally the issues should be fixed now.First I forgot that you have to use devtools to install the package and Second, they made an update of the visNtwork today (I actually checked this morning and it was fine...) I adapted the functions accordingly and it works again.

Let me know if it works :)

Best, 

Guillaume

**Comment by TomHarrop** [comment]
OK, looks great now! I had to run it as `shiny::runGitHub("guillaumelobet/psim")`, it didn't like `runGitHub("psim","guillaumelobet”)`.

I also had to run the command twice—the first time I ran it I got this:

```
Loading required package: visNetwork
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘visNetwork’
Downloading git repo https://github.com/dataknowledge/visNetwork
Installing visNetwork
Installing 1 packages: htmlwidgets
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/xm/qr0vxq4930zb6n1tcnp1sr180000gn/T/Rtmpphu0SQ/filec901cadf25b'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

* installing *source* package ‘visNetwork’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (visNetwork)

Listening on http://127.0.0.1:5375
Error in tag("div", list(...)) : 
  could not find function "visNetworkOutput"
```

so I guess it didn't attach `visNetwork` after installing it.
